# This file contains values from Cookiecutter

default_context:
  project_name: "reperio"
  project_description: "Reperio is a cvisualization utility for Apache Nutch data structures."
  organization: "lewismc"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.9
  github_name: "lewismc"
  email: "lewismc@apache.org"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
